### ISSUE TITLE
پرایوت نبودن ریپازیتوری

### ISSUE THREAD

**Issue by Sahandi81** [aliqasemzadeh/personal#1]
به نظرم اشتباها یک سری از ریپازیتوری هاتون رو فراموش کردید پرایوت کنید.
منطقا به بنده مربوط نیست ولی صرفا خواستم اطلاع رسانی کنم خدمتت اگر اشتباهی پیش اومده باشه پیگیری کنی.

**Comment by aliqasemzadeh** [comment]
@Sahandi81 
سلام
این ریپازیتوری عمومی هست
